import React, { useState, useEffect } from 'react';
import { Box, Skeleton, Dialog, DialogTitle, DialogContent, DialogActions, IconButton, Avatar } from '@mui/material';
import { BarChart3, Download, FileText, Calendar, Filter, TrendingUp, Eye, X, User, Clock, Star, CheckCircle } from 'lucide-react';
import { useAuth } from '../context/AuthContext';
import { supabase } from '../lib/supabaseClient';
import PageHeader from '../components/PageHeader';
import StatCard from '../components/StatCard';
import { reportService } from '../services/reportService';
import { departmentService } from '../services/departmentService';
import { attendanceService } from '../services/attendanceService';

const Reports = () => {
  const { user } = useAuth();
  const [reports, setReports] = useState([]);
  const [deptStats, setDeptStats] = useState([]);
  const [loading, setLoading] = useState(true);
  const [filterDate, setFilterDate] = useState(new Date().toLocaleDateString('en-CA', { timeZone: 'Asia/Kolkata' }));
  const [selectedReport, setSelectedReport] = useState(null);
  const [kpis, setKpis] = useState({ total: 0, attendance: 0, hours: 0 });

  useEffect(() => {
    const fetchData = async () => {
      try {
        setLoading(true);
        // If filterDate is set, we use a more specific query
        const [reportList, depts, attendance] = await Promise.all([
          filterDate ? reportService.getReportsByDate(filterDate) : reportService.getAllReports(),
          departmentService.getDepartmentStats(),
          attendanceService.getTodayStats()
        ]);

        setReports(reportList);
        setDeptStats(depts);
        setKpis({
          total: reportList.length,
          attendance: Math.round((attendance.present / (depts.reduce((a, b) => a + b.total, 0) || 1)) * 100),
          hours: reportList.length > 0 
            ? (reportList.reduce((acc, r) => acc + (parseFloat(r.total_working_hours) || 0), 0) / reportList.length).toFixed(1)
            : 0
        });
      } catch (err) {
        console.error('Reports Fetch Error:', err);
      } finally {
        setLoading(false);
      }
    };
    fetchData();

    // Real-time: refresh when reports are submitted/updated
    const channel = supabase
      .channel('hr_reports_realtime')
      .on('postgres_changes', { event: '*', schema: 'public', table: 'daily_reports' }, () => fetchData())
      .subscribe();

    return () => {
      supabase.removeChannel(channel);
    };
  }, [filterDate]);

  const handleDownload = (rep) => {
    const content = `
DAILY WORK REPORT
-----------------
Employee Name: ${rep.profiles?.full_name || 'N/A'}
Employee ID: ${rep.user_id}
Date: ${new Date(rep.report_date).toLocaleDateString()}

1. TASKS PLANNED TODAY:
${rep.tasks_planned || 'N/A'}

2. TASKS COMPLETED:
${rep.tasks_completed || 'N/A'}

3. WORK IN PROGRESS:
${rep.work_in_progress || 'N/A'}

4. TOMORROW PLAN:
${rep.tomorrow_plan || 'N/A'}

5. METRICS:
Total Working Hours: ${rep.total_working_hours}
Productivity Rating: ${rep.productivity_rating}/10

6. ADDITIONAL NOTES:
${rep.additional_notes || 'None'}

-----------------
Generated by EMS Pro
    `.trim();

    const element = document.createElement("a");
    const file = new Blob([content], {type: 'text/plain'});
    element.href = URL.createObjectURL(file);
    element.download = `Report_${rep.profiles?.full_name?.replace(/\s+/g, '_')}_${rep.report_date}.txt`;
    document.body.appendChild(element);
    element.click();
    document.body.removeChild(element);
  };

  const handleReview = async (rep) => {
    try {
      await reportService.reviewReport(rep.id, rep.user_id, user.id);
      
      // Update local state
      setReports(prev => prev.map(r => r.id === rep.id ? { ...r, status: 'reviewed' } : r));
      
      // Feedback
      const Swal = (await import('sweetalert2')).default;
      Swal.fire({
        icon: 'success',
        title: 'Report Reviewed',
        text: `Notification sent to ${rep.profiles?.full_name}`,
        toast: true,
        position: 'top-end',
        showConfirmButton: false,
        timer: 3000
      });
    } catch (err) {
      alert('Failed to review report: ' + err.message);
    }
  };

  return (
    <div className="animate-in fade-in duration-500">
      <PageHeader title="Reports & Analytics" subtitle="Insights and exportable reports">
        <button className="btn-ems btn-ems-primary">
          <Download size={16} /> Export All
        </button>
      </PageHeader>

      {/* Summary Stats */}
      <div className="grid grid-cols-1 sm:grid-cols-3 gap-5 mb-6">
        <StatCard title="Reports Submitted" value={loading ? '...' : kpis.total.toString()} icon={FileText} color="#4f46e5" bgColor="#eef2ff" trend="up" trendValue="+12" />
        <StatCard title="Attendance Rate" value={loading ? '...' : `${kpis.attendance}%`} icon={TrendingUp} color="#10b981" bgColor="#ecfdf5" />
        <StatCard title="Avg. Hours/Day" value={loading ? '...' : `${kpis.hours}h`} icon={BarChart3} color="#f59e0b" bgColor="#fffbeb" />
      </div>

      {/* Charts Grid */}
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6 mb-6">
        {/* Attendance Trends (2/3) */}
        <div className="lg:col-span-2">
          <Box className="card-ems-static" sx={{ p: 3, height: '100%' }}>
            <div className="flex justify-between items-center mb-5">
              <h3 className="text-base font-bold text-slate-900">Attendance Trends</h3>
              <span className="badge-pill primary">Last 7 Days</span>
            </div>
            <div className="flex items-end gap-1.5 px-2 rounded-xl bg-slate-50 border border-slate-100" style={{ height: 220, padding: '16px' }}>
              {[60, 45, 80, 55, 90, 70, 85].map((h, i) => (
                <div key={i} className="flex-1 rounded-t transition-all hover:opacity-100" style={{
                  height: `${h}%`,
                  background: `linear-gradient(to top, #4f46e5, #818cf8)`,
                  opacity: 0.7,
                  minWidth: 8,
                  borderRadius: '4px 4px 0 0',
                }} />
              ))}
            </div>
            <div className="flex justify-between mt-3 text-xs text-slate-400 font-semibold px-2">
              <span>Mon</span><span>Tue</span><span>Wed</span><span>Thu</span><span>Fri</span><span>Sat</span><span>Sun</span>
            </div>
          </Box>
        </div>

        {/* Department Distribution (1/3) */}
        <div>
          <Box className="card-ems-static" sx={{ p: 3, height: '100%' }}>
            <h3 className="text-base font-bold text-slate-900 mb-5">Dept. Distribution</h3>
            <div className="flex flex-col gap-3">
              {loading ? (
                [1,2,3,4].map(i => <Skeleton key={i} height={30} />)
              ) : deptStats.map((item, i) => (
                <div key={i}>
                  <div className="flex justify-between items-center mb-1 text-sm">
                    <span className="font-semibold text-slate-700">{item.name}</span>
                    <span className="font-bold text-slate-500">{item.total} emps</span>
                  </div>
                  <div className="progress-ems">
                    <div className="progress-ems-fill" style={{ width: `${Math.min(100, (item.total/kpis.total)*100)}%` }} />
                  </div>
                </div>
              ))}
            </div>
          </Box>
        </div>
      </div>

      {/* Reports Table */}
      <Box className="card-ems-static" sx={{ overflow: 'hidden' }}>
        <Box sx={{ p: 3, pb: 0, mb: 3, display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
          <h3 className="text-base font-bold text-slate-900">Daily Submission Log</h3>
          <div className="flex items-center gap-3">
             <label className="text-xs font-bold text-slate-400 uppercase">Filter Date:</label>
             <input 
               type="date" 
               className="form-input-ems" 
               style={{ width: 160, height: 36, fontSize: 13 }}
               value={filterDate}
               onChange={(e) => setFilterDate(e.target.value)}
             />
             <button className="btn-ems btn-ems-secondary" style={{ height: 36 }} onClick={() => setFilterDate('')}>Clear</button>
          </div>
        </Box>
        <div className="table-responsive">
          <table className="table-ems" style={{ width: '100%' }}>
            <thead>
              <tr>
                <th>Employee</th>
                <th>Submission Date</th>
                <th>Content Snippet</th>
                <th style={{ textAlign: 'center' }}>Status</th>
                <th style={{ textAlign: 'right' }}>Actions</th>
              </tr>
            </thead>
            <tbody>
              {loading ? (
                [1,2,3].map(i => <tr key={i}><td colSpan={5}><Skeleton height={40} /></td></tr>)
              ) : reports.length > 0 ? reports.map((rep, i) => (
                <tr key={rep.id}>
                  <td>
                    <div className="flex items-center gap-2">
                      <FileText size={15} className="text-indigo-500" />
                      <span className="text-sm font-semibold text-slate-800">{rep.profiles?.full_name || 'User'}</span>
                    </div>
                  </td>
                  <td className="text-sm text-slate-500">{new Date(rep.created_at).toLocaleDateString()}</td>
                  <td className="text-sm text-slate-500 truncate max-w-xs">{rep.tasks_completed || 'No summary'}</td>
                  <td className="text-center">
                    <span className={`badge-pill ${rep.status === 'reviewed' ? 'success' : 'warning'}`}>
                      {rep.status === 'reviewed' ? 'Reviewed' : 'Pending'}
                    </span>
                  </td>
                  <td style={{ textAlign: 'right' }}>
                    <div className="flex justify-end gap-1">
                      {rep.status !== 'reviewed' && (
                        <button className="btn-icon-ems" style={{ width: 32, height: 32 }} onClick={() => handleReview(rep)} title="Mark as Reviewed">
                          <CheckCircle size={14} className="text-emerald-600" />
                        </button>
                      )}
                      <button className="btn-icon-ems" style={{ width: 32, height: 32 }} onClick={() => setSelectedReport(rep)} title="View Details">
                        <Eye size={14} className="text-indigo-600" />
                      </button>
                      <button className="btn-icon-ems" style={{ width: 32, height: 32 }} onClick={() => handleDownload(rep)} title="Download Report">
                        <Download size={14} />
                      </button>
                    </div>
                  </td>
                </tr>
              )) : (
                <tr><td colSpan={5} className="text-center py-10">No reports found.</td></tr>
              )}
            </tbody>
          </table>
        </div>
      </Box>

      {/* View Report Dialog */}
      <Dialog 
        open={!!selectedReport} 
        onClose={() => setSelectedReport(null)}
        maxWidth="md"
        fullWidth
        PaperProps={{ sx: { borderRadius: '20px', p: 1 } }}
      >
        {selectedReport && (
          <>
            <DialogTitle sx={{ fontWeight: 800, display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
              <div className="flex items-center gap-3">
                <Avatar sx={{ bgcolor: '#eef2ff', color: '#4f46e5' }}>
                  <User size={20} />
                </Avatar>
                <div>
                  <h3 className="text-lg font-extrabold text-slate-900">{selectedReport.profiles?.full_name}</h3>
                  <p className="text-xs text-slate-500 font-medium">{new Date(selectedReport.report_date).toLocaleDateString(undefined, { dateStyle: 'long' })}</p>
                </div>
              </div>
              <IconButton onClick={() => setSelectedReport(null)}><X size={20} /></IconButton>
            </DialogTitle>
            <DialogContent dividers sx={{ borderBottom: 'none' }}>
              <div className="grid grid-cols-1 md:grid-cols-2 gap-6 pt-2">
                <div className="flex flex-col gap-6">
                  <section>
                    <h4 className="text-[10px] font-black text-slate-400 uppercase tracking-widest mb-2">Planned Today</h4>
                    <p className="text-sm text-slate-700 bg-slate-50 p-3 rounded-xl border border-slate-100 whitespace-pre-wrap">{selectedReport.tasks_planned}</p>
                  </section>
                  <section>
                    <h4 className="text-[10px] font-black text-slate-400 uppercase tracking-widest mb-2">Completed Tasks</h4>
                    <p className="text-sm text-slate-700 bg-emerald-50 p-3 rounded-xl border border-emerald-100 whitespace-pre-wrap font-medium">{selectedReport.tasks_completed}</p>
                  </section>
                  <section>
                    <h4 className="text-[10px] font-black text-slate-400 uppercase tracking-widest mb-2">Additional Notes</h4>
                    <p className="text-sm text-slate-500 italic bg-slate-50 p-3 rounded-xl border border-slate-100">{selectedReport.additional_notes || 'No additional notes provided.'}</p>
                  </section>
                </div>

                <div className="flex flex-col gap-6">
                  <section>
                    <h4 className="text-[10px] font-black text-slate-400 uppercase tracking-widest mb-2">Work In Progress</h4>
                    <p className="text-sm text-slate-700 bg-amber-50 p-3 rounded-xl border border-amber-100 whitespace-pre-wrap">{selectedReport.work_in_progress || 'None'}</p>
                  </section>
                  <section>
                    <h4 className="text-[10px] font-black text-slate-400 uppercase tracking-widest mb-2">Tomorrow's Plan</h4>
                    <p className="text-sm text-slate-700 bg-indigo-50 p-3 rounded-xl border border-indigo-100 whitespace-pre-wrap">{selectedReport.tomorrow_plan}</p>
                  </section>
                  
                  <div className="grid grid-cols-2 gap-4">
                    <div className="bg-slate-900 rounded-2xl p-4 text-white">
                      <div className="flex items-center gap-2 mb-1 opacity-60">
                        <Clock size={14} />
                        <span className="text-[10px] font-bold uppercase">Hours</span>
                      </div>
                      <p className="text-xl font-black">{selectedReport.total_working_hours}h</p>
                    </div>
                    <div className="bg-indigo-600 rounded-2xl p-4 text-white">
                      <div className="flex items-center gap-2 mb-1 opacity-60">
                        <Star size={14} />
                        <span className="text-[10px] font-bold uppercase">Rating</span>
                      </div>
                      <p className="text-xl font-black">{selectedReport.productivity_rating}/10</p>
                    </div>
                  </div>
                </div>
              </div>
            </DialogContent>
            <DialogActions sx={{ p: 3, pt: 0 }}>
              <button className="btn-ems btn-ems-secondary w-full" onClick={() => setSelectedReport(null)}>Close Report</button>
            </DialogActions>
          </>
        )}
      </Dialog>
    </div>
  );
};

export default Reports;
